name: decklist_to_pdf
description: A Dart translation of the original Python decklist_to_pdf script.
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.6
  image: ^4.0.17
  pdf: ^3.10.1
  path: ^1.8.2

# No dev dependencies for this simple port
